### ISSUE TITLE
Cannot access to PyTorch build artifacts from hud.pytorch.org/pr

### ISSUE THREAD

**Issue by mstfbl** [pytorch/pytorch-ci-hud#112]
Access to PyTorch build artifacts from `hud.pytorch.org/pr/${PR_NUM}` is not working after GitHub login and authentication. Page displayed is the same after refreshing except for the `authorize_github` code. This occurs on incognito/anonymous browser modes on different browsers such as Chrome, Edge and Firefox.

![login-attempt-1](https://user-images.githubusercontent.com/5262061/132776929-1bb84dea-78cf-48b6-bed5-bd547d8859b2.png)

**Comment by malfet** [comment]
@mstfbl can you please share a screenshot of your authorized github oauth apps, as document in https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/reviewing-your-authorized-integrations (which I assume can be done by following https://github.com/settings/applications )

This is how it looks for me:
![image](https://user-images.githubusercontent.com/2453524/132777388-4378d6f8-f318-42b2-9114-0710ce4921aa.png)

**Comment by malfet** [comment]
Ok, I think I know what's going on:
![image](https://user-images.githubusercontent.com/2453524/132777810-3ef0dc92-76c4-4c3a-9f1a-7390a6c45012.png)
@driazati can you please renew the cert

**Comment by driazati** [comment]
Cert has been fixed, I tested out log-out -> log in and it seems to work. @mstfbl please re-open if you're still having the same issue

**Comment by mstfbl** [comment]
Hi all, thank you for the fix, I'm now able to access the artifacts.

**Comment by Psoffie009** [comment]
> Access to PyTorch build artifacts from `hud.pytorch.org/pr/${PR_NUM}` is not working after GitHub login and authentication. Page displayed is the same after refreshing except for the `authorize_github` code. This occurs on incognito/anonymous browser modes on different browsers such as Chrome, Edge and Firefox.
> 
> ![login-attempt-1](https://user-images.githubusercontent.com/5262061/132776929-1bb84dea-78cf-48b6-bed5-bd547d8859b2.png)

**Comment by Psoffie009** [comment]
> Hi all, thank you for the fix, I'm now able to access the artifacts.

**Comment by Psoffie009** [comment]
> Ok, I think I know what's going on:
> ![image](https://user-images.githubusercontent.com/2453524/132777810-3ef0dc92-76c4-4c3a-9f1a-7390a6c45012.png)
> @driazati can you please renew the cert
